### PR TITLE
Add support for --with-lmdb. Make TC optional.

### PR DESCRIPTION
**Pull request by keltia**
Not sure how to specify a default so I made both optional.

### CODE REVIEW

**Comment by alexpearce** [comment]
This means that if the user does not specify at least one on `--tokyo-cabinet` or `--with-lmdb`, there will be no cache backend. Do we want that?

**Comment by keltia** [comment]
I can add a check to make one of them default, just didn't want to complicate things.

**Comment by flatcap** [comment]
Currently, if you only specify `--enable-hcache` then you get `--with-tokyocabinet` for free.
**Currently**: No change is needed.

However, I'm about to merge some hcache changes which will mean that you have to specify a backend
(the changes also allow **multiple backends** to be compiled-in).
**Soon**: The formula will need to select a default.

The alternative route is to default to building **all** the backends -- if you don't have the libraries, then some will be ignored.  A quick test shows a `neomutt` with all six backends is only 40K (3%) bigger than one with no hcache at all.

**Comment by keltia** [comment]
If we can build all the backends (but how is the one you want specified in `.muttrc`?), I'm for it.  I don't mind having a default, I just want to be able to override it (and using lmdb of course)

**Comment by flatcap** [comment]
There will be a new variable: `$header_cache_backend`

**Comment by keltia** [comment]
Ok, in the meantime, what should I do?  test for tokoycabinet/lmdb and just pick up a default if none are specified?  My guess is that it is mostly for the bottle, people using `-s` will know :)

**Comment by flatcap** [comment]
Hi @keltia.
I'm sorry that this PR got forgotten about.
Are you still interested in making changes to the formula?

Below is a list of all the "interesting" options.
I'd love to see as many options as possible in the formula.

Please can you help?
Thanks, @flatcap.

---

Not needed:
* `--enable-hcache` &mdash; This can be removed

Header Cache &mdash; NeoMutt now allows, **zero, one or more** of these:
* `--with-tokyocabinet` &mdash; Use tokyocabinet for the header cache
* `--with-kyotocabinet` &mdash; Use kyotocabinet for the header cache
* `--with-lmdb` &mdash; Use LMDB for the header cache
* `--with-gdbm` &mdash; Use gdbm for the header cache
* `--with-qdbm` &mdash; Use qdbm for the header cache
* `--with-bdb` &mdash; Use BerkeleyDB for the header cache

Features &mdash; Large features (only notmuch has extra dependencies):
* `--enable-compressed` &mdash; Enable compressed folders support
* `--enable-sidebar` &mdash; Enable Sidebar support
* `--enable-nntp` &mdash; Enable NNTP support
* `--enable-notmuch` &mdash; Enable NOTMUCH support

Mailboxes:
* `--enable-imap` &mdash; Enable IMAP support
* `--enable-pop` &mdash; Enable POP3 support
* `--enable-smtp` &mdash; Include internal SMTP relay support

Misc:
* `--enable-debug` &mdash; Enable debugging support
* `--enable-gpgme` &mdash; Enable GPGME support
* `--with-mixmaster` &mdash; Include Mixmaster support
* `--with-gnutls` &mdash; enable TLS support using gnutls

**Comment by keltia** [comment]
I was told in the past by Homebrew people that they did not want to include all possible options (it was when I asked `--enable-compressed` for the "official" mutt formula)…  If you'd rather go that way (and I think it would be fine to have more, if only for the reason that MacPorts does too), I can help.

To be honest, some of them should be made default anyway (even if it add external deps) like `compressed`, `imap` and `smtp`.  `hcache` ought to be the default as well.  Not sure whether it is worth letting people choose between 5 or 6 options, most will not care as long as the feature is fast (lmdb or TC being my favourites amongst the fastest).

**Comment by flatcap** [comment]
> I think it would be fine to have more

Great.

> if only for the reason that MacPorts does too)

:-)

> To be honest, some of them should be made default anyway
> like compressed, imap and smtp

Agreed.

> (even if it add external deps)

OK, I'll leave that decision to you.
As long as there's a "disabled" option.

> hcache ought to be the default as well.
> Not sure whether it is worth letting people choose between 5 or 6 options,

Yes.  Of course we can influence their decision with the instructions:
- Tokyo (default - safe choice)
- LMDB (recommended - high performance)
- something else
- something else

> most will not care as long as the feature is fast (lmdb or TC being my favourites amongst the fastest).

LMDB did very well in [our tests](https://www.neomutt.org/contrib/hcache-bench).

> I can help.

Thanks.  Any questions, let me know.

**Comment by flatcap** [comment]
Hi @keltia.  How are things going?
There will probably be a new release in the next week.
Do you have any other changes to add before that?

**Comment by allykzam** [comment]
May want to add some kind of message that displays when updating to a build of neomutt that includes this change; I just updated and relaunched neomutt, and got `Error in /Users/amazingant/.mutt/muttrc, line 14: header_cache: unknown variable`. Reinstalling with `--with-tokyo-cabinet` fixed it of course, but it took about 20 minutes of digging to find out that this used to be specified by default and I now has to be manually specified.

**Comment by jindraj** [comment]
> Header cache support is optional now. You can chosoe between lmdb,tokyo-cabinet or none which is default.
> If you want header cache support reinstall neomutt with --with-lmdb or --with-tokyo-cabinet.

It will display in `brew info neomutt` and after installation if built without both lmdb and tokyo-cabinet. 
Does this message describe change enough?

**Comment by flatcap** [comment]
Sorry about that @amazingant.

I've just looked back though all the old Formulae and it seems that 'tokyocabinet' has always defaulted to on.  Sorry, I suggested that @jindraj change that.

**Comment by allykzam** [comment]
@jindraj sounds good to me 👍 

@flatcap no worries, I try to read through changelogs when I install updates for frequently-used things, but of course for homebrew that usually ends up being the upstream notes. Thank you all for your time and energy just maintaining this in the first place :)

**Pull request closed without merging**
